---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      labels:
        app: javawebapp
    spec:
      containers:
        - name: webappcontainer
          image: d654/jenkins-docker:devtest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: websvc
spec:
  type: LoadBalancer
  selector:
    app: javawebapp
  ports:
    - port: 80           # Public-facing port
      targetPort: 8080   # Port inside container where your app is running
